### ISSUE TITLE
Possible X11 configure fix for lib64

### ISSUE THREAD

**Issue by marXtevens** [wmcbrine/PDCurses#108]
I had problems with configure, and then with make, trying to build PDCurses under Centos 8, so I made the following change to configure. I'm a noob at modifying applications, so be kind :-D Is there anything else I should supply?

> [xmas@reindeer x11]$ diff configure configure.2021-01-20.xmas
4281,4283c4281
< mh_lib64_dirs="$x_libraries `echo "$ac_x_includes $ac_x_header_dirs" | sed s/include/lib64/g`"
< 
< mh_lib_dirs="$x_libraries `echo "$ac_x_includes $ac_x_header_dirs" | sed s/include/lib/g` $mh_lib64_dirs"
\-\-\-
> mh_lib_dirs="$x_libraries `echo "$ac_x_includes $ac_x_header_dirs" | sed s/include/lib/g`"
[xmas@reindeer x11]$

The modified configure script is attached.
[configure.zip](https://github.com/wmcbrine/PDCurses/files/5850954/configure.zip)

 ... Mark A. Stevens

**Comment by wmcbrine** [comment]
So, the two things you'd need:

1. `configure` is built from other files -- configure.ac and aclocal.m4 -- by autoconf. You`d want to figure out how to modify it there, rather than directly.
2. More importantly, you'd need to show that the change didn't adversely affect other distros, like Debian. "lib64" is already in the tested paths, and there have been a few related changes, most recently bb87f9d95af4c77131d907005434c44c91f69363 .

...and actually, as I look at it, your patch doesn't appear to be based on either the current code, nor on the last release, but on an earlier version (3.8?). So, that'd be the zeroth thing.
