### ISSUE TITLE
Foreground colour not being used via SDL2 

### ISSUE THREAD

**Issue by jeringa** [wmcbrine/PDCurses#119]
Background colours seem to be set & used correctly. But the foreground colour is always white.
This shows up in my code and also the "testcurs" demo program
Haven't tested other back-ends yet (X11, wincon, etc)

**Comment by Bill-Gray** [comment]
Thank you;  that's definitely a bug.

Not sure this is _the_ problem,  but it's certainly _a_ problem : in this situation,  the `foregr` variable in `pdcdisp.c` can be negative.  Then it's used as an index into the `pdc_color[]` array and read a pseudo-random value in front of said array.  Add an `assert( foregr >= 0);` statement before the various uses of `foregr` as an array index,  and it'll trip.

This is now [fixed in PDCursesMod](https://github.com/Bill-Gray/PDCursesMod/commit/e19ea211fce26dcb3de267fe59ed7defe7cae07b).  At least,  I think it is;  the handling of default colors is strange and complex.  The bug is identical,  even though the code has diverged a bit since forking.  The `init_col` and `newtest` demos (which are PDCursesMod-specific) now work correctly,  even with PDC_BACKGROUND set.

And I see the same problem occurs in the SDL1 code,  which uses near-identical logic.

**Comment by wmcbrine** [comment]
I'm pretty sure this is the same issue as #114 and #112.

This has nothing to do with negative foregr.

**Comment by Bill-Gray** [comment]
Errrmmm... I don't see how the SDL version would cause `foregd` to be negative.  And I don't see how a negative array index here fails to be a problem.

Using array indices of `(foregd > 0 ? foregd : 0)` instead of plain `foregd` fixes the bug described in this issue.  It doesn't do anything for issues #112 or #114,  though you did briefly get my hopes up that there might be some weird relationship here (with SDL reacting to undefined indices differently between versions).

**Comment by wmcbrine** [comment]
> Using array indices of `(foregd > 0 ? foregd : 0)` instead of plain `foregd` fixes the bug described in this issue.

It doesn't, at all. I can only assume that you're wildly misreading the OP.
