### ISSUE TITLE
window not showing in pdcurses for dos

### ISSUE THREAD

**Issue by SrinSS01** [wmcbrine/PDCurses#131]
I wrote a small C++ program in dosbox and compiled it using Borland Turbo C++ compiler
```c++
#include <curses.h>
#include <string.h>
#include <iostream.h>
#include <stdlib.h>

class Curs {
private:
	int width, height;
public:
	Curs() {
		initscr();
		noecho();
		cbreak();
		if (!has_colors()) {
			endwin();
			cerr << "colors not supported" << endl;
			exit(1);
		}
		start_color();
		getmaxyx(stdscr, height, width);
	}
	~Curs() { endwin(); }
	int get_w() const { return width; }
	int get_h() const { return height; }
};

enum Colors {
	RED_WHITE = 1, BLACK_WHITE, WHITE_BLUE, BLUE_BLUE
};

class Window {
private:
	 WINDOW* handle;
public:
	Window(
		int x, int y,
		int w, int h,
		int background,
		int border = 1
	): handle(newwin(h, w, y, x)) {
		wbkgd(handle, COLOR_PAIR(background));
		if (border) box(handle, 0, 0);
		wrefresh(handle);
		refresh();
	}
	~Window() { delwin(handle); }
	WINDOW* get_handle() const { return handle; }
};

int main() {
	Curs cur;
	int w = cur.get_w();
	int h = cur.get_h();
	init_pair(RED_WHITE, COLOR_RED, COLOR_WHITE);
	init_pair(BLACK_WHITE, COLOR_BLACK, COLOR_WHITE);
	init_pair(WHITE_BLUE, COLOR_WHITE, COLOR_BLUE);
	init_pair(BLUE_BLUE, COLOR_BLUE, COLOR_BLUE);
	Window game(0, 0, w, h - 8, WHITE_BLUE, 1);
	WINDOW* game_handle = game.get_handle();
	wgetch(game_handle); // tried both wgetch
	getch(); // and getch but window still not showing
	return 0;
}
```

**Comment by Bill-Gray** [comment]
FWIW,  it also fails with ncurses and PDCursesMod (VT port),  so it's not really a PDCurses-specific issue.  I don't see offhand what's wrong.

**Comment by wmcbrine** [comment]
Your call to `refresh()` after `wrefresh(handle)` overwrites your new window with `stdscr`. Remember always that the forms of the curses functions that don't specify a window, operate on `stdscr` -- i.e. `refresh()` is really `wrefresh(stdscr)`... and nothing else. It's specifically *not* a generic function to call after refreshing each window. Since stdscr covers the screen, it covers any other window you draw (depending on the refresh order).

In general, you should chose either to work with stdscr, or work with user-created windows and ignore the stdscr functions. The only reason I'd even consider calling `refresh()` in a program like this is if I were determined to use `getch()` -- which of course is really `wgetch(stdscr)`, which means that it does an implicit `wrefresh(stdscr)`. But, better to leave that out, and stick to `wgetch(game_handle)`.

Anyway, take out those two lines, and your program works as intended. And as noted, this is not specific to PDCurses or to DOS.
