### ISSUE TITLE
SDL2 Alt key not propogated

### ISSUE THREAD

**Issue by bjadamson** [wmcbrine/PDCurses#142]
Hello, it's possible I'm doing something wrong -- but I'm using the SDL2 port, trying to detect ALT keys (ALT+h), etc..

When your checking for alt keys (alternate?) I needed to add a check for alt as well:
```c++
if (key && ((SP->key_modifiers & PDC_KEY_MODIFIER_CONTROL) || (SP->key_modifiers & PDC_KEY_MODIFIER_ALT)))
```

The code currently only checks for control.
https://github.com/wmcbrine/PDCurses/blob/f2d31a2633eb042f7bf1f79cba81522915a04579/sdl2/pdckbd.c#L299-L300

I could be super far off here and handling of alt keys should be done in a different way, so I wanted to run this past you and see what you think.

Thanks for your library, it's been a joy to use.

**Comment by Bill-Gray** [comment]
Thanks for the report and fix.  I'd heard about this problem a couple of weeks ago,  determined it had been broken since at least 2020,  and hadn't figured out a fix.

Part of what threw me is that the error only affects Microsoft Windows.  Applying your fix to Linux and building `testcurs` and running the input test,  hitting Alt-keys gets you duplicate key presses.  On Linux, `_handle_alt_keys()` is called earlier in the function,  and you don't want to call it twice.

I think the fix will involve setting a `we_already_called_handle_alt_keys` Boolean to `TRUE`,  and then (at lines 299-300) only calling `_handle_alt_keys()` if that Boolean is still `FALSE`.

That fix would work,  but we'd still have the question of why it works one way on Linux and a different way in Microsoft Windows.  SDLn is supposed to (and for the most part does) get you around these platform-specific details.  So there may be some "gotchas" not yet figured out... but I think you've at least got us on the right track.

**Comment by bjadamson** [comment]
Thanks -- it took me a minute to get back to you but looks good to me. I agree that it behaving on linux like that is weird.
