### ISSUE TITLE
Changes from 3.4 to 3.5 on Windows?

### ISSUE THREAD

**Issue by matkuki** [wmcbrine/PDCurses#20]
Hi guys,

I am trying to get version 3.5 to work on Windows 10 x64 as a DLL, without much success. The *initscr*, *printw*, *refresh* and *endwin* function do nothing.
Then I downloaded and compiled version 3.4 from source and it works without problems.

I am using the compiled DLL with the Nim programming language.
My specs:
- OS: Windows 10 x64
- Compiler: gcc (x86_64-win32-seh-rev1, Built by MinGW-W64 project) 7.2.0

Equivalent C sample code to my Nim code:
```c
initscr();
printw(curses_version());
refresh();
endwin();
```

I apologize if I am missing something basic, but I only recently started playing around with PDCurses and am not well versed in its concepts.

**Comment by wmcbrine** [comment]
Using my psychic debugging powers...

Everything is, I suspect, working as designed. I think the problem is that you're exiting the program immediately, and expecting it to leave output on the screen. That works in the Windows console version of 3.4, but it isn't a behavior you should rely on -- some other ports of PDCurses never even write to a console. And in 3.5, the Windows console port, by default, switches to its own buffer while running, and switches back at the end, so it leaves nothing on screen. See here:

https://github.com/wmcbrine/PDCurses/pull/4

You can try "set PDC_RESTORE_SCREEN=0", as described there; but the simplest thing would be to put a getch() before the endwin(), so that the program stays open until the user presses a key.

**Comment by matkuki** [comment]
Hey @wmcbrine ,
Your psychic powers are spot on! Both solutions work like a charm!
Thanks for the explanation.
