### ISSUE TITLE
wincon: re-add HAVE_INFOEX

### ISSUE THREAD

**Issue by GitMensch** [wmcbrine/PDCurses#28]
Moved from discussion in https://github.com/wmcbrine/PDCurses/pull/27.

@wmcbrine removed the `HAVE_INFOEX` definition from win32/pdcwin.h with d9fb37d ("Dropped support for Digital Mars.") which breaks building with other environments like MinGW, too.

While mingw-w64 has `CONSOLE_SCREEN_BUFFER_INFOEX` it is generally not available with the "original" MinGW environment, even when updated (there is a [MinGW ticket](https://osdn.net/projects/mingw/ticket/38187) for this issue).

But even with an updated version the "new" wincon.h wouldn't be available for many old environments.

Despite the minimal clutter the old defines add there is no bad part about it (it doesn't break new environments), therefore I'd like to see it back with the minimal entry in wincon/pdcwin.h like:

```c
#if !defined(HAVE_INFOEX) && !defined(HAVE_NO_INFOEX)
# define HAVE_INFOEX
#endif
```

This way all environments will default to have it and when building with "old" environments the option "-DHAVE_NO_INFOEX` exists.

**Comment by wmcbrine** [comment]
I disagree that the clutter is "minimal" and has "no bad part"; I find it ugly. It was a happy day for me when I thought I could take it out. (sigh)

I gotta admit, I was surprised to see the OSDN project you linked to. It doesn't show up in the first five pages of Google results for "mingw", and AFAICT, MinGW.org itself only points to SourceForge, where nothing has been updated since 2013; even the Wikipedia article on MinGW says "[t]he development of the original MinGW project has halted in 2013", although I now see that it does also link to OSDN.

**Comment by Bill-Gray** [comment]
Though fortunately,  not enough conflict to ruin your basic reasoning,  i.e.:  add an INFOEX=N flag for such compilers.  I should have pulled it before the renaming occurred;  I don't recall why I didn't.

I _may_ have been thinking about the desirability of maintaining some level of compatibility with William McBrine's branch.  He has,  of course,  now removed this capability.  I'm not ready to do that yet (nor are you or others).  But that does mean we no longer have to try to make our logic resemble that of "official" PDCurses;  we can do it however we wish,  and your method seems straightforward enough.

The one minor change I'd suggest is that instead of making a new `PDCCFLAGS` in the makefile (now `makefile.mng`),  I'd just add the `-DHAVE_INFOEX` or `-DHAVE_NO_INFOEX` directly to the already existing `CFLAGS`.  Do that (or tell me why we need a new variable),  and I'll pull it in.

We do have the issue that William has incorporated quite a few nice improvements,  particularly to the Windows console platform,  and not all of them have percolated down to this fork.  At some point,  I'll have to go through the various commits to PDCurses/wmcbrine and add them to PDCurses/Bill-Gray (I've already done this with a few).

(Alternatively,  the improvements in _this_ fork would get pulled up into PDCurses/wmcbrine,  and some already have been.  But I don't expect most of them ever will; incorporating the wmcbrine improvements here seems more likely to occur.)

**Comment by wmcbrine** [comment]
You know, looking at this again now, I think part of my opposition was that I'd planned to drop a lot more of the "ugly code" than I actually got around to doing. If it's just a matter of adding back this one structure... I might as well do it. I still feel like PDCurses shouldn't have to keep supporting outdated compile environments, but I seem to be outvoted. ;)

Rather than re-adding HAVE_INFOEX per se, I propose just HAVE_NO_INFOEX to bracket the structure. I'll accept the INFOEX=N from your Bill Gray patch as well.

**Comment by wmcbrine** [comment]
Changes posted now: https://github.com/wmcbrine/PDCurses/commit/1cb6b51907c8646af5dd01a645f934213fb5f92d

(Not yet tested.)

**Comment by GitMensch** [comment]
Tested and works as expected:

* MINGW32 and MINGW64 build without any issues (demos only working in OS directly)
* MinGW builds with `INFOEX=N` (and demos working within MSYS and OS)

Thank you for coming back and finally solving this.
