### ISSUE TITLE
Create PDC_version_info structure and option to receive it at run-time

### ISSUE THREAD

**Issue by GitMensch** [wmcbrine/PDCurses#45]
Providing this helps external applications to get detailed information about

* the actual version, both for compilation (PDCurses has only `PDC_BUILD` so far, a more detailed version would be nice) *and* at run-time:
```c
#define PDC_VER_MAJOR    3
#define PDC_VER_MINOR    6
#define PDC_VER_CHANGE   1
#define PDC_VER_YEAR   2018
#define PDC_VER_MONTH   12
#define PDC_VER_DAY     02

#define PDC_BUILD (PDC_VER_MAJOR*1000 + PDC_VER_MINOR *100 + PDC_VER_CHANGE)
```
* the build options (size of chtype, wide, ...), available at run-time
* the actual variant of PDCurses in use at run-time

This was previously committed to the BillGray fork in 9b2cdad531e52999c3d166cb7b35f85f86b598eb, 08fd141dc649899af823ff868ad4e594e4d78d80, 42ff4f6832019da17bf535c38fc0fd9944ae9648.

Using the exact same structure and external name would obviously be very good as it also allows to switch the shared object versions (as long as no other ABI-difference is used, but luckily there aren't so much "external" differences).

**Comment by GitMensch** [comment]
I see the version numbering was changed with af16a73b89912120ed9c246df6b4e51ec61fa821, can you add the `struct PDC_version_info` and use it, too?

**Comment by wmcbrine** [comment]
I've been thinking about this since BG first did it. I'm going to implement it, soon. But it probably won't be compatible with what's in the BG fork.

Although I like the basic idea, I have issues with the design. I don't want to add a third part to the version number; I don't want to enumerate the ports, or include anything in curses.h that makes any reference to specific ports. I'd quibble with some other, minor choices.

More fundamentally, I've been reluctant to commit to a stable ABI, in the way that this kind of extension would (to me) imply.

Even more than that, there's the issue of whether it really makes sense to use PDCurses as a DLL at all. It's a small library, especially by modern standards. Redundant, statically-linked copies aren't going to be that much of an issue. And I know I wrote about using DLLs to swap between, e.g., console and SDL, but that's not really a good idea, either -- apart from the amusement value -- since console apps require a controlling terminal, which just becomes extraneous with SDL; and apps built to run without a controlling terminal (as -mwindows or -subsystem:windows) can't then use the console DLL. (Although I suppose SDL vs. wingui or wincon vs. vt would work better, in BG's fork.)

Despite these concerns, I'm persuaded. I could even do it in a way that's more-or-less compatible with BG's -- just filling in zeros in the unused fields; maybe setting "port" to 8, which I'd define as "use PDC_sysname() to look it up" -- but to me that seems less than elegant.

**Comment by Bill-Gray** [comment]
In re third part to the version number : perhaps this can be zero for a stably released version?  For example,  I'm currently at 4.0.4.  If I tweak it a bit in development,  it goes to 4.0.5.  If I produce a new stable,  release version,  it goes to 4.1.0.  Once I start tweaking _that_ in development,  the third number increments.
I don't plan to commit to a stable ABI either.  (I have plans to change the ABI in my fork,  to get rid of the `xbuttons` array,  expand the mouse `buttons` array accordingly,  add your `pdc_set_bold` function,  and probably quite a bit more in the course of grabbing some goodies from your branch.)  Version numbering,  at least from my viewpoint,  is separate from ABI stability.
In re dropping DLLs : at one point,  I did make use of that ability.  In theory,  it can be a useful test ("hmm,  it works with Wincon, SDL1,  SDL2,  and WinGUI... VT seems to be the odd guy out.")  In practice,  I've recompiled rather than swapping DLLs.

**Comment by wmcbrine** [comment]
https://github.com/wmcbrine/PDCurses/commit/9b493204fbdbf6d5658dd08064c0fa0cb266ae26

Example of use:

    #include "curses.h"

    int main()
    {
        PDC_VERSION info;

        PDC_get_version(&info);
        printf("flags: %d\nbuild: %d\nmajor: %d\nminor: %d\n"
               "csize: %d\nbsize: %d\n",
               info.flags, info.build, info.major, info.minor,
               info.csize, info.bsize);

        return 0;
    }

**Comment by GitMensch** [comment]
Can you please extend `PDC_VERSION` as follows?`

```c
enum PDC_port
{
    PDC_PORT_X11 = 0,
    PDC_PORT_WINCON = 1,
    PDC_PORT_DOS = 3,  /* skipped 2 on purpose... */
    PDC_PORT_OS2 = 4,
    PDC_PORT_SDL1 = 5,
    PDC_PORT_SDL2 = 6,
};

typedef struct
{
    short flags;          /* flags OR'd together (see below) */
    short build;          /* PDC_BUILD at compile time */
    unsigned char major;  /* PDC_VER_MAJOR */
    unsigned char minor;  /* PDC_VER_MINOR */
    unsigned char change; /* PDC_BUILD  % 100 */
    unsigned char csize;  /* sizeof chtype */
    unsigned char bsize;  /* sizeof bool */
    enum PDC_port port;
} PDC_VERSION;
```

**Comment by wmcbrine** [comment]
No.

The platform name is available via PDC_sysname().

**Comment by GitMensch** [comment]
sysname returns a string - the point is to have an easy way to check it in the code = enum value, not strncmp.

In any case: What about the third part of the version string?
