### ISSUE TITLE
start_color broken?

### ISSUE THREAD

**Issue by GitMensch** [wmcbrine/PDCurses#50]
If it is then it is a long standing bug.

The PDCurses documentation and the comments in pdcurses/color.c say:

> `start_color()` initializes eight basic colors (black, red, green, yellow, blue, magenta, cyan, and white)

which is 100% identical to the ncurses documentation but likely should be (according to the switched default colors):

> `start_color()` initializes eight basic colors (black, blue, green, yellow, red, magenta, cyan, and white)

But the real bug seems not the long-standing documentation but that after `start_color()` the first 8 pairs are all identical (foreground white, background black) . Shouldn't they be different?

I've glanced at the PDCurses source but could not find any place where those default pairs should be set. What did I miss?

**Comment by GitMensch** [comment]
Answer to my last question:  `start_color` just initializes the color constants that may be used later, not the color pairs. The difference between ncurses and PDCurses is another one, tested with

```c

	initscr ();
	if (has_colors ()) {
		short	fore_color = 0;
		short	back_color = 0;
		start_color ();
		pair_content ((short)0, &fore_color, &back_color);
		fprintf (stderr, "colors 0: %d, %d\n", fore_color, back_color);
		pair_content ((short)4, &fore_color, &back_color);
		fprintf (stderr, "colors 4: %d, %d\n", fore_color, back_color);
		pair_content ((short)7, &fore_color, &back_color);
		fprintf (stderr, "colors 7: %d, %d\n", fore_color, back_color);
		pair_content ((short)8, &fore_color, &back_color);
		fprintf (stderr, "colors 8: %d, %d\n", fore_color, back_color);
		pair_content ((short)10, &fore_color, &back_color);
		fprintf (stderr, "colors 10: %d, %d\n", fore_color, back_color);
		pair_content ((short)COLOR_PAIRS - 2, &fore_color, &back_color);
		fprintf (stderr, "colors %d: %d, %d\n", COLOR_PAIRS - 2, fore_color, back_color);
		pair_content ((short)COLOR_PAIRS - 1, &fore_color, &back_color);
		fprintf (stderr, "colors %d: %d, %d\n", COLOR_PAIRS - 1, fore_color, back_color);
	}
```

result with PDCurses:

~~~
colors 0: 7, 0
colors 4: 7, 0
colors 8: 7, 0
colors 10: 7, 0
colors 254: 7, 0
colors 255: 7, 0
~~~

ncurses:

~~~
olors 0: 7, 0
colors 4: 0, 0
colors 7: 0, 0
colors 8: 0, 0
colors 10: 0, 0
colors 65534: 0, 0
colors 65535: 0, 0
~~~

I'd consider ncurses' initialization correct, what do you say?

**Comment by wmcbrine** [comment]
AFAICT, both are "correct" -- trying to use a color pair you haven't set up is undefined behavior. Of the two, I think I prefer PDCurses' (you'll get monochrome text instead of blankness).

**Comment by GitMensch** [comment]
Fastest user-closed bug-report ever ;-)

**Comment by Bill-Gray** [comment]
I guess I'd lean (but only _very_ slightly) to having color 0 be white on black,  and the other colors something like red on yellow.  A mildly nauseating color choice would emphasize that you really should be using `init_pair()` instead of relying on undefined behavior. As it stands,  you might not recognize use of uninitialized pairs until you tried to port to ncurses.  Then you'll wonder why your text vanished,  and the reason wouldn't be quite as obvious.
On a side note,  I'm interested to see that Simon has COLOR_PAIRS = 64K in ncurses.   (I get 256 in xterm.)  That does allow one to show any color pairing (of 256 foreground colors times 256 background colors),  _if_ your terminal happens to have COLOR_PAIRS = 64K.
