### ISSUE TITLE
subwin compatibility problem

### ISSUE THREAD

**Issue by webfolderio** [wmcbrine/PDCurses#51]
Hi,

The following subwin example\* didn't work with PDCurses.
It shows just blank page instead of sub windows.
is this might be caused by a compatibility problem?

Environment: _Windows 10 (1803), Visual Studio 2017 & PDCurses wincon_

\* Programmer's Guide to NCurses, page 286

```c
#include <curses.h>

int main(void)
{
	WINDOW *subby,*sonny;
	int row,col;

	initscr();
	start_color();
	init_pair(1,COLOR_WHITE,COLOR_BLUE);
	init_pair(2,COLOR_YELLOW,COLOR_RED);

	subby = newwin(10,30,10,40);
	wbkgd(subby,COLOR_PAIR(1));
	getparyx(subby,row,col);
	wprintw(subby,"This subwin's org: %d, %d.",row,col);
	wrefresh(subby);
	
	sonny = subwin(subby,7,30,13,40);
	wbkgd(sonny,COLOR_PAIR(2));
	getparyx(sonny,row,col);
	wprintw(sonny,"This subwin's org: %d, %d.",row,col);
	wrefresh(sonny);

	getch();

	endwin();
	return 0;
}
```
<img width="463" alt="example_subwin" src="https://user-images.githubusercontent.com/23472649/51903487-5aca8380-23cd-11e9-925e-ecdc08a0adb1.png">

**Comment by wmcbrine** [comment]
The code as you've posted it doesn't work with ncurses, either. Because you've changed one critical line from the example in the page image. If you change that back, it works in both.

Remember that getch() is equivalent to wgetch(stdscr), and wgetch() does an implicit refresh() on the window. Since stdscr had never been refreshed at that point, the whole screen-covering window of blankness is displayed, overwriting everything else.
