### ISSUE TITLE
Redirection is not support.

### ISSUE THREAD

**Issue by maximhesed** [wmcbrine/PDCurses#52]
I clone your repo and built pdcurses in ../wincon.
I got pdcurses.a. Ok. Next, I decided write simple test program and compile it:

main.c:
```
#include <stdio.h>

#include <curses.h>

int
main(void) {
    initscr();
    printw("Hello, World!\n");
    refresh();
    endwin();
    return 0;
}
```

How I compiled it: gcc -I ~/source/PDCurses/ main.o ~/source/PDCurses/wincon/pdcurses.a -o prog

It's good. Next, I run ./prog.exe and see an error: Redirection is not supported.

I searching solution this problem, but i found only for nano text editor (it's run perfectly for me), because i'm writing here.

I'm using cygwin in windows.

**Comment by maximhesed** [comment]
I'm using cygwin in windows.

**Comment by Bill-Gray** [comment]
This has come up several times.  (Sufficiently often that I'm now thinking perhaps the error message should perhaps be more informative.)  There's some good discussion of the problem at
https://github.com/Bill-Gray/PDCurses/issues/15
Essentially,  `mintty` doesn't support the Windows console API;  it uses more "traditional" escape sequences,  a la VT-xxx and xterm.  So there's no way to get the WinCon flavor of PDCurses to work in mintty.  You _can_ use SDL,  or (in my fork) the VT or Windows GUI flavors.  The VT flavor would be the way to go if you're insistent on the display being within the console,  rather than as a separate window.

**Comment by wmcbrine** [comment]
There are some options for running wincon with Cygwin --

1. Start any PDCurses-linked app from mintty as "cmd /c start progname" instead of just "./progname". This will launch a standard Windows console in a new window and run the app there.

2. Open a regular "cmd" console window instead of mintty, go to the Cygwin directory, and run cygwin.bat. This creates a Cygwin environment within a standard console window, so you can run "./progname" directly. Recent versions of the Windows console have gained a lot of support for escape sequences, so this may not even be a problem for Cygwin's more Unix-y apps.
