### ISSUE TITLE
No putp()/tigetflag()/tigetnum()/... (term.h) makes it messy to build Python wheels

### ISSUE THREAD

**Issue by ulfalizer** [wmcbrine/PDCurses#55]
These were removed in commit 6b56929 ("Eliminated term.h, terminfo.c; moved mvcur() to move.c").

[_cursesmodule.c](https://github.com/python/cpython/blob/master/Modules/_cursesmodule.c) from Python unconditionally calls them (though the `term.h` #include itself is optional (`HAVE_TERM_H`)).

Just recording an actual issue caused by the `term.h` removal.

Do you think the stubs could be brought back, even if `term.h` is left out?

**Comment by wmcbrine** [comment]
In retrospect, I think it was a terrible mistake to ever include them. I'm not inclined to bring them back.

Linking _cursesmodule.c against PDCurses didn't actually work anyway, did it? I mean, in terms of the result being usable. That's why there are multiple alternative Python curses interfaces to work with PDCurses, is it not?

I think the correct approach would be to make Python's curses library more portable. Relying on non-working stubs is not the way. (And, it's mostly not possible to make them work -- PDCurses just isn't designed that way at all.)

**Comment by ulfalizer** [comment]
Works fine after #defining some macros.

The README in the [windows-curses](https://github.com/zephyrproject-rtos/windows-curses) repository has an overview of how `_cursesmodule.c` fits into things. I think all Python/PDCurses integrations link against it. The [prebuilt wheels](https://www.lfd.uci.edu/~gohlke/pythonlibs/#curses) from Christoph Gohlke also do.

We've been using it to make a [menuconfig interface](https://docs.zephyrproject.org/latest/application/index.html#overriding-the-default-configuration) available on Windows in addition to Linux. The only special-casing in the code is related to resizing (see `_get_wch_compat()` in [menuconfig.py](https://github.com/zephyrproject-rtos/zephyr/tree/master/scripts/kconfig)).

**Comment by ulfalizer** [comment]
Random idea:

Do you think they could be hidden behind a PDCurses compile-time setting? That way, you'd have to explicitly ask for them, and you wouldn't get code silently failing because it expects the stubs to work.

Can see if you don't want to litter the code up like that though.

**Comment by cgohlke** [comment]
Try to compile (and link) a copy of `terminfo.c` when building the `_cursesmodule` Python extension with the new PDCurses. Works for me.

**Comment by ulfalizer** [comment]
@cgohlke 
Seems like the least painful option. Thanks for the idea!
