### ISSUE TITLE
Problem compiling PDCurses with code::block mingw (Windows 10)

### ISSUE THREAD

**Issue by AmigaBlitter** [wmcbrine/PDCurses#96]
Hello,

i tried to compile PDCurses in Windows 10, using Code:Block 20 with mingw. I tried to follow the instructions in the README.md file.
When i fired the command make -f makefilename (mingw32-make.exe) i got the following message: Makefile:90: *** multiple target patterns.  Stop.

I tried to create a codeblock project but, when the project starts to build (after building some .o files) stop with the error:
PDCurses-3.9\dos\pdcdisp.c|10|error: storage size of 'regs' isn't known|

Any info on this?

Thank you in advance
Kind regards
AB

**Comment by wmcbrine** [comment]
> When i fired the command make -f makefilename (mingw32-make.exe)

Is that meant to be an exact representation of what you typed? Because it should look more like:

    mingw32-make -f Makefile

or, in this case -- since "Makefile" is already the default:

    mingw32-make

This is assuming that you're already in the "wincon" directory, which is probably the one you want, not...

> PDCurses-3.9\dos\pdcdisp.c|10|error: storage size of 'regs' isn't known|

The "dos" directory is for the MS-DOS port. That's probably not what you want.

**Comment by AmigaBlitter** [comment]
Thank you for the reply. 
It's mingw32-make -f Makefile. Tried with mingw32-make only too, but same result.
As per the second issue, i removed all non necessary dirs, such OS2, X11 and so on... keeping the pdcurses, common, wincon and demos directories and the library has been built.

Thank you very much.
Kind regards
AB

**Comment by wmcbrine** [comment]
You didn't need to delete the other platforms. Just don't try to build them. :)
